import { BlogPost, Booking, Consultation } from "./types";

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "hi", label: "हिंदी" },
  { code: "te", label: "తెలుగు" },
  { code: "ta", label: "தமிழ்" },
  { code: "es", label: "Español" },
] as const;

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    heroTitle: "Healthcare Anywhere, Anytime with AI-Assisted Telemedicine Kiosks",
    heroSubtitle: "Bringing expert medical consultation and intelligent health screening closer to communities through advanced AI and telemedicine technology.",
    bookDemo: "Book Demo",
    learnMore: "Learn More",
    featuresTitle: "Revolutionary Kiosk Capabilities",
    featuresSubtitle: "Equipped with state-of-the-art diagnostic sensors and powered by clinical-grade AI algorithms.",
    solutions: "Solutions",
    technology: "AI Technology",
    kiosk: "Interactive Kiosk",
    services: "Services",
    pricing: "Pricing",
    caseStudies: "Case Studies",
    blog: "Insights Blog",
    contact: "Contact & Demo",
    dashboard: "Provider Portal",
    aboutUs: "About Us",
    patientBenefits: "For Patients",
    providerBenefits: "For Healthcare Providers",
    allRightsReserved: "All rights reserved.",
    footerDisclaimer: "MediConnect AI provides preliminary triage and decision-support. Actual diagnoses are provided by certified clinical practitioners.",
  },
  hi: {
    heroTitle: "एआई-सहायता प्राप्त टेलीमेडिसिन कियोस्क के साथ कहीं भी, कभी भी स्वास्थ्य सेवा",
    heroSubtitle: "उन्नत एआई और टेलीमेडिसिन तकनीक के माध्यम से विशेषज्ञ चिकित्सा परामर्श और बुद्धिमान स्वास्थ्य जांच को समुदायों के करीब लाना।",
    bookDemo: "डेमो बुक करें",
    learnMore: "अधिक जानें",
    featuresTitle: "क्रांतिकारी कियोस्क क्षमताएं",
    featuresSubtitle: "अत्याधुनिक नैदानिक ​​सेंसरों से लैस और नैदानिक-ग्रेड एआई एल्गोरिदम द्वारा संचालित।",
    solutions: "समाधान",
    technology: "एआई तकनीक",
    kiosk: "इंटरैक्टिव कियोस्क",
    services: "सेवाएं",
    pricing: "मूल्य निर्धारण",
    caseStudies: "केस स्टडीज",
    blog: "ब्लॉग",
    contact: "संपर्क और डेमो",
    dashboard: "प्रदाता पोर्टल",
    aboutUs: "हमारे बारे में",
    patientBenefits: "मरीजों के लिए",
    providerBenefits: "प्रदाताओं के लिए",
    allRightsReserved: "सर्वाधिकार सुरक्षित।",
    footerDisclaimer: "मेडीकनेक्ट एआई प्रारंभिक ट्राइएज और निर्णय-समर्थन प्रदान करता है। वास्तविक निदान प्रमाणित चिकित्सकों द्वारा प्रदान किए जाते हैं।",
  },
  te: {
    heroTitle: "AI-సహాయక టెలిమెడిసిన్ కియోస్క్‌లతో ఎక్కడైనా, ఎప్పుడైనా వైద్య సేవలు",
    heroSubtitle: "అధునాతన AI మరియు టెలిమెడిసిన్ టెక్నాలజీ ద్వారా నిపుణులైన వైద్య సంప్రదింపులను మరియు స్మార్ట్ హెల్త్ స్క్రీనింగ్‌ను ప్రజలకు మరింత దగ్గర చేయడం.",
    bookDemo: "డెమో బుక్ చేయండి",
    learnMore: "మరింత తెలుసుకోండి",
    featuresTitle: "అద్భుతమైన కియోస్క్ సామర్థ్యాలు",
    featuresSubtitle: "అత్యాధునిక డయాగ్నస్టిక్ సెన్సార్లతో కూడిన మరియు క్లినికల్-గ్రేడ్ AI అల్గారిథమ్‌లతో పనిచేసే వ్యవస్థ.",
    solutions: "పరిష్కారాలు",
    technology: "AI టెక్నాలजी",
    kiosk: "ఇంటరాక్టివ్ కియోస్క్",
    services: "సేవలు",
    pricing: "ధరలు",
    caseStudies: "కేస్ స్టడీస్",
    blog: "బ్లాగ్",
    contact: "సంప్రదించండి",
    dashboard: "పోర్టల్",
    aboutUs: "మా గురించి",
    patientBenefits: "రోగుల కొరకు",
    providerBenefits: "వైద్య సంస్థల కొరకు",
    allRightsReserved: "అన్ని హక్కులు ప్రత్యేకించబడినవి.",
    footerDisclaimer: "మెడికనెక్ట్ AI ప్రాథమిక స్క్రీనింగ్ మాత్రమే అందిస్తుంది. తుది రోగ నిర్ధారణ ధృవీకరించబడిన వైద్యుల ద్వారానే చేయబడుతుంది.",
  },
  ta: {
    heroTitle: "AI-உதவியுடனான டெலிமெடிசின் கியோஸ்க்களுடன் எங்கும், எப்போது வேண்டுமானாலும் மருத்துவம்",
    heroSubtitle: "மேம்பட்ட AI மற்றும் டெலிமெடிசின் தொழில்நுட்பத்தின் மூலம் நிபுணத்துவ மருத்துவ ஆலோசனை மற்றும் புத்திசாலித்தனமான சுகாதார பரிசோதனையை மக்களுக்கு நெருக்கமாக கொண்டு சேர்த்தல்.",
    bookDemo: "டெமோ பதிவு செய்க",
    learnMore: "மேலும் அறிய",
    featuresTitle: "புரட்சிகர கியோஸ்க் திறன்கள்",
    featuresSubtitle: "அதிநவீன கண்டறியும் சென்சார்கள் மற்றும் மருத்துவ தர AI அல்காரிதம்களால் இயக்கப்படுகிறது.",
    solutions: "தீர்வுகள்",
    technology: "AI தொழில்நுட்பம்",
    kiosk: "கியோஸ்க் விவரங்கள்",
    services: "சேவைகள்",
    pricing: "கட்டணங்கள்",
    caseStudies: "ஆய்வுகள்",
    blog: "வலைப்பதிவு",
    contact: "தொடர்பு & டெமோ",
    dashboard: "மருத்துவர் தளம்",
    aboutUs: "எங்களை பற்றி",
    patientBenefits: "நோயாளிகளுக்கு",
    providerBenefits: "மருத்துவமனைகளுக்கு",
    allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    footerDisclaimer: "மெடிகனெக்ட் AI ஆரம்பகட்ட பரிசோதனை வழிகாட்டுதலை மட்டுமே வழங்குகிறது. இறுதி சிகிச்சை சான்றளிக்கப்பட்ட மருத்துவர்களால் மட்டுமே வழங்கப்படும்.",
  },
  es: {
    heroTitle: "Atención Médica en Cualquier Lugar y Momento con Quioscos de Telemedicina Asistidos por IA",
    heroSubtitle: "Acercando consultas médicas expertas y cribados de salud inteligentes a las comunidades mediante IA avanzada y tecnología de telemedicina.",
    bookDemo: "Reservar Demo",
    learnMore: "Saber Más",
    featuresTitle: "Capacidades Revolucionarias del Quiosco",
    featuresSubtitle: "Equipado con sensores de diagnóstico de última generación y potenciado por algoritmos de IA de grado clínico.",
    solutions: "Soluciones",
    technology: "Tecnología IA",
    kiosk: "Quiosco Interactivo",
    services: "Servicios",
    pricing: "Precios",
    caseStudies: "Casos Clínicos",
    blog: "Blog de Ideas",
    contact: "Contacto & Demo",
    dashboard: "Portal de Proveedor",
    aboutUs: "Nosotros",
    patientBenefits: "Para Pacientes",
    providerBenefits: "Para Proveedores",
    allRightsReserved: "Todos los derechos reservados.",
    footerDisclaimer: "MediConnect AI proporciona triaje preliminar y soporte de decisiones. Los diagnósticos reales son provistos por profesionales médicos certificados.",
  },
};

export const FEATURES = [
  {
    id: "f-1",
    title: "AI Symptom Assessment",
    description: "Multi-modal conversation engine conducts clinical-grade history taking and assigns real-time triage risk scores.",
    category: "AI Engine",
  },
  {
    id: "f-2",
    title: "Remote Doctor Consultation",
    description: "Crystal clear, ultra-low-latency 4K video connects users to general practitioners or top specialists instantly.",
    category: "Telehealth",
  },
  {
    id: "f-3",
    title: "Vital Signs Monitoring",
    description: "Integrated FDA-approved sensors for blood pressure, pulse oximetry, thermometer, and high-fidelity ECG.",
    category: "Hardware",
  },
  {
    id: "f-4",
    title: "Electronic Medical Records",
    description: "Instant cloud syncing generates encrypted PDF reports and updates the central electronic health records natively.",
    category: "Cloud",
  },
  {
    id: "f-5",
    title: "E-Prescription Services",
    description: "Secure, automated doctor signatures direct medicine orders to your chosen local pharmacy or a physical kiosk printer.",
    category: "Clinical",
  },
  {
    id: "f-6",
    title: "Multi-Language Support",
    description: "Inclusive natural voice translation accommodates local vernaculars including Hindi, Telugu, Tamil, Spanish, and English.",
    category: "Accessibility",
  },
  {
    id: "f-7",
    title: "Secure Cloud Platform",
    description: "Military-grade data encryption, robust HIPAA compliance framework, and secure biometric authentication.",
    category: "Security",
  },
  {
    id: "f-8",
    title: "Real-Time Health Analytics",
    description: "Aggregated, anonymous population-health streams predict local disease outbreaks and flag demographic trends.",
    category: "Analytics",
  },
];

export const STATISTICS = [
  { value: "500+", label: "Kiosks Deployed", sub: "Globally active" },
  { value: "100K+", label: "Patients Served", sub: "Underserved & corporate" },
  { value: "98%", label: "Satisfaction Rate", sub: "User feedback average" },
  { value: "24/7", label: "Medical Support", sub: "Round-the-clock availability" },
];

export const BENEFITS = {
  patients: [
    { title: "Immediate Access", desc: "Skip 4-hour clinic queues; receive preliminary triage in under 3 minutes." },
    { title: "Zero Transit Expense", desc: "No need for costly travel to urban centers for standard checkups." },
    { title: "Clinical-Grade Sensors", desc: "Get medical readings that are certified, precise, and completely secure." },
    { title: "Personalized Digital History", desc: "Own your continuous biometric timeline on an encrypted, accessible account." },
  ],
  providers: [
    { title: "Limitless Reach", desc: "Establish micro-clinics in factories, village blocks, or corporate lobbies." },
    { title: "Streamlined Triage", desc: "AI filters low-risk cases, freeing up physician bandwidth for critical care." },
    { title: "Dynamic Analytics", desc: "Access continuous dashboards mapping demographic vitals and utilization logs." },
    { title: "Drastic Overhead Savings", desc: "Cut operational costs of staffing full physical clinics by up to 65%." },
  ],
};

export const TESTIMONIALS = [
  {
    quote: "The MediConnect Kiosk in our village changed everything. I checked my chest tightness and immediately spoke with a cardiologist in Chennai. It saved my life.",
    author: "Ramanathan Swamy",
    role: "Farmer, Tamil Nadu Rural Outreach",
    type: "patient",
    rating: 5,
  },
  {
    quote: "Our employees love having a clinic-grade kiosk in our tech park lobby. It's fast, private, and gives everyone an easy pulse on their daily health vitals.",
    author: "Shreya Sen",
    role: "HR Director, Innovate Solutions",
    type: "patient",
    rating: 5,
  },
  {
    quote: "I was highly skeptical of telehealth, but the diagnostic sensors are incredibly precise. Having high-res throat scans and real-time ECGs makes remote clinical decisions safe.",
    author: "Dr. Rajesh Kurup",
    role: "MD, Internal Medicine, Apollo Clinics",
    type: "provider",
    rating: 5,
  },
  {
    quote: "We've deployed 40 kiosks to ease triage pressure in our public hospital overflow wings. Low-risk patients get routed to remote specialists in record time.",
    author: "Dr. Laura Vance",
    role: "Chief of Staff, Metropolitan Health Systems",
    type: "provider",
    rating: 5,
  },
  {
    quote: "My mother had a severe fever at night. The kiosk translated Telugu, diagnosed acute tonsillitis with Dr. Priya, and printed her prescription instantly. Absolute blessing.",
    author: "Koteswara Rao",
    role: "Civil Engineer, Guntur District",
    type: "patient",
    rating: 5,
  },
];

export const TIMELINE = [
  { year: "2023", title: "Inception & ISO certification", desc: "Founded with a mission to decentralize rural primary care; certified HIPAA compliant." },
  { year: "2024", title: "First 100 Rural Deployments", desc: "Partnered with national health programs to deploy 100 solar-powered kiosks." },
  { year: "2025", title: "Enterprise and Corporate Expansion", desc: "Launched dedicated corporate wellness kiosk with multi-lead ECG and automated blood pressure cuff." },
  { year: "2026", title: "AI Gen 3.5 Diagnostic Integration", desc: "Integrated real-time neural symptom-history taking to achieve 98% triage accuracy." },
];

export const LEADERSHIP = [
  { name: "Dr. Vikram Aditya", role: "Co-Founder & CEO", bio: "Former WHO Digital Health advisor with 18 years in rural telehealth development.", img: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400" },
  { name: "Ananya Deshmukh", role: "Chief Technology Officer", bio: "Ex-Google Senior Staff Engineer specializing in embedded medical systems and ML model compression.", img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400" },
  { name: "Marcus Thorne", role: "Head of Medical Devices", bio: "Biomedical engineer with 15 years experience leading FDA clinical validation pipelines.", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400" },
];

export const KIOSK_COMPONENTS = [
  {
    name: "HD Consultation Camera",
    desc: "4K robotic PTZ camera with dual-lens macro zooming for ultra-high-resolution dermatological, ophthalmic, and ENT throat inspections.",
    spec: "4K UHD, 60fps, Auto-Focus, Polarized ring flash",
    icon: "Video",
  },
  {
    name: "Touchscreen Display",
    desc: "21.5-inch medical-grade touch console with anti-microbial glass, guiding users step-by-step in multiple languages with native audio prompts.",
    spec: "IPS LCD, 500 nits, Anti-glare, Chemically strengthened",
    icon: "Tv",
  },
  {
    name: "Blood Pressure Monitor",
    desc: "Fully automated clinical cuff that inflates comfortably with voice-guided instructions, mapping diastolic and systolic history.",
    spec: "Precision: ±3 mmHg, Cuff Range: 22-42 cm",
    icon: "Heart",
  },
  {
    name: "Pulse Oximeter",
    desc: "Non-invasive optical finger sensor measuring blood oxygen saturation (SpO2) and heart rate levels in less than 10 seconds.",
    spec: "SpO2 Range: 70-100% (accuracy ±1%), Photoplethysmograph",
    icon: "Activity",
  },
  {
    name: "Medical Thermometer",
    desc: "Infrared temporal/forehead scanner that records accurate core body temperature automatically as the patient sits at the station.",
    spec: "Non-contact IR, Precision: ±0.1°C / ±0.2°F",
    icon: "Thermometer",
  },
  {
    name: "12-Lead ECG Device",
    desc: "Compact clinical electrocardiograph tracking real-time chest/limb cardiac waveforms. Instantly flags arrhythmias and ischemia.",
    spec: "12-channel simultaneous acquisition, 1000Hz sampling",
    icon: "Activity",
  },
  {
    name: "Integrated Weight Scale",
    desc: "Heavy-duty smart pressure scale embedded directly into the kiosk platform base to record continuous BMI metrics.",
    spec: "Capacity: up to 250kg, resolution: 100g, auto BMI calculator",
    icon: "Layers",
  },
  {
    name: "AI Diagnostic Module",
    desc: "Embedded neural processing unit conducting local symptom parsing, voice dictation translation, and sensor triage mapping.",
    spec: "NPU 26 TOPS, Local encrypted LLM-triage integration",
    icon: "Cpu",
  },
  {
    name: "Document Scanner",
    desc: "Medical records and identity scanner supporting insurance card capture, identity verification, and local diagnostic record uploads.",
    spec: "600 DPI optical color scanner, secure optical character recognition",
    icon: "FileText",
  },
  {
    name: "Prescription Printer",
    desc: "Secure thermal dispenser printing barcoded digital prescriptions, referral letters, and health summaries on durable medical paper.",
    spec: "Thermal roll, 300 DPI, secure watermarked print paper",
    icon: "Printer",
  },
];

export const SOLUTIONS = [
  {
    id: "sol-1",
    title: "Rural Healthcare Solution",
    subtitle: "Reinventing Village Care",
    desc: "Bringing high-fidelity medicine to villages, remote clinics, and tribal belts. Our kiosks are solar-compatible, require minimal maintenance, and operate on highly optimized low-bandwidth satellite networks (2G/3G fallbacks). Enables local healthcare workers to manage screenings smoothly.",
    bullets: [
      "Solar-powered battery backup for 12 hours of uptime",
      "Offline cache syncing for regions without cellular cover",
      "Simple, audio-guided vernacular instructions",
      "Centralized clinic referral & emergency transit alerts",
    ],
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "sol-2",
    title: "Corporate Wellness Solution",
    subtitle: "Smart Office Health Stations",
    desc: "Boost workplace productivity and slash healthcare insurance overhead. Employees conduct swift, private 4-minute vital checkups during break hours, consult mental health specialists confidentially, and track chronic parameters without taking a full day off work.",
    bullets: [
      "Seamless integration with company insurance networks",
      "Instant biometric login with secure NFC/ID card scans",
      "Private video consultations for stress and mental health",
      "Custom company-wide health statistics & trends report",
    ],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "sol-3",
    title: "Hospital Extension Solution",
    subtitle: "AI-Powered Overflow & Triage",
    desc: "Decongest crowded outpatient departments (OPDs) and emergency rooms. Kiosks placed in lobby wings collect comprehensive symptoms and vital profiles automatically, instantly categorizing patients into clear risk tiers so clinicians focus on critical emergencies.",
    bullets: [
      "Full HL7 / FHIR compliance for flawless hospital EMR syncing",
      "Automated clinical risk stratification (Red/Yellow/Green tiers)",
      "Direct routing of non-emergent cases to remote on-call doctors",
      "Drastically reduces patient waiting room times by up to 70%",
    ],
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "sol-4",
    title: "Government Healthcare Programs",
    subtitle: "Mass Public Health Infrastructure",
    desc: "Equipping government medical centers and community centers with public diagnostic hubs. Supports national immunization campaigns, anonymous disease surveillance systems, and scalable epidemiologic response tracking during viral outbreaks.",
    bullets: [
      "Highly affordable public health screening with low per-capita costs",
      "Dynamic data streams for real-time viral fever and outbreak mapping",
      "Secure vaccination booking, verification, and PDF certification",
      "Extremely robust build quality designed for heavy public usage",
    ],
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=600",
  },
];

export const SERVICES = [
  { title: "General Physician", desc: "Expert assessment for common illnesses like flus, infections, minor injuries, and skin conditions.", cost: "$", time: "Instant (5 min wait)" },
  { title: "Specialist Consultation", desc: "Cardiology, dermatology, oncology, and endocrinology portals via structured clinical appointments.", cost: "$$$", time: "Within 24 hours" },
  { title: "Mental Health Services", desc: "Private, anonymous video counseling, CBT support, and anxiety management with licensed therapists.", cost: "$$", time: "Scheduled/On-demand" },
  { title: "Chronic Care Management", desc: "Structured tracking for Diabetes, Hypertension, COPD. Monitors vitals continuously and adjusts prescriptions.", cost: "$", time: "Continuous tracking" },
  { title: "Preventive Screening", desc: "Standard wellness audits including BMI, lipid-level risk models, high-fidelity blood pressure tracking.", cost: "Free", time: "Self-guided (4 mins)" },
  { title: "Health Education", desc: "Interactive customized tutorials on nutrition, cardiac health, diabetes preventative measures on-screen.", cost: "Free", time: "Interactive videos" },
  { title: "Medication Management", desc: "Direct pharmacist syncing, prescription renewals, and physical kiosk prescription printouts.", cost: "$", time: "Instant print" },
  { title: "Follow-up Care", desc: "Structured post-discharge checkups. Share daily vital telemetry directly with your chief operating physician.", cost: "$", time: "Physician-coordinated" },
];

export const PRICING_PLANS = [
  {
    name: "Starter Plan",
    desc: "Perfect for standalone clinics, small village hubs, or single offices looking to launch basic telehealth capabilities.",
    monthlyPrice: 499,
    yearlyPrice: 399,
    features: [
      "1 Medical-Grade Kiosk",
      "Basic AI Symptom Assessor",
      "Standard Telehealth Video link",
      "Integrated BP & SpO2 sensors",
      "Standard EMR secure sync",
      "Email & business hour support",
      "HIPAA Compliant storage",
    ],
    action: "Get Started",
    badge: "Clinics",
  },
  {
    name: "Professional Plan",
    desc: "Designed for corporate parks, healthcare chains, and hospital networks requiring advanced diagnostic sensors.",
    monthlyPrice: 1299,
    yearlyPrice: 1049,
    features: [
      "Multiple Kiosk Deployments",
      "Advanced Predictive AI Engine",
      "12-Lead ECG Device included",
      "NFC/ID Biometric Smart-login",
      "Custom EHR/FHIR API Integration",
      "24/7 Priority Support SLAs",
      "Multi-Language Audio System",
      "Dynamic utilization dashboard",
    ],
    action: "Schedule Implementation",
    badge: "Popular Choice",
    popular: true,
  },
  {
    name: "Enterprise Plan",
    desc: "Tailored for state governments, defense, public health programs, and national hospital networks with custom needs.",
    monthlyPrice: "Custom",
    yearlyPrice: "Custom",
    features: [
      "Unlimited Kiosk Fleet",
      "Custom AI Models (fine-tuned)",
      "Solar Power Battery Packs",
      "Ruggedized All-Weather Enclosure",
      "On-premise Database hosting option",
      "Dedicated Technical Account Manager",
      "Tailored branding & custom decals",
      "National Disease Surveillance pipeline",
    ],
    action: "Contact Enterprise Sales",
    badge: "Enterprise",
  },
];

export const CASE_STUDIES = [
  {
    id: "cs-1",
    title: "Rural Healthcare Transformation",
    tag: "Public Health Deployment",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=600",
    location: "Chittoor District, Andhra Pradesh",
    problem: "Villagers walked over 25 kilometers of rough terrain to access the nearest primary health center. Delayed checkups resulted in high hypertension and diabetes complication rates.",
    solution: "Deployed 15 solar-powered MediConnect AI Kiosks in local village panchayats, managed by trained community health workers.",
    results: [
      { metric: "12,000+", label: "Consultations Completed" },
      { metric: "45%", label: "Reduction in ER emergency visits" },
      { metric: "3.5 hrs", label: "Travel time saved per patient" },
      { metric: "94%", label: "Early-stage diagnosis rate" },
    ],
  },
  {
    id: "cs-2",
    title: "Smart City Health Initiative",
    tag: "Government Program",
    image: "https://images.unsplash.com/photo-1544027993-37dbfe43562a?auto=format&fit=crop&q=80&w=600",
    location: "Pune Urban Micro-Clinics",
    problem: "Urban low-income settlements experienced massive public clinic waiting times, forcing day-wage laborers to lose essential income to get simple cold medicines.",
    solution: "Installed 30 high-definition MediConnect kiosks in metro stations and urban community centers, operating 24 hours a day.",
    results: [
      { metric: "65,000+", label: "Citizens Treated" },
      { metric: "4.2 mins", label: "Average Triage Duration" },
      { metric: "$180K+", label: "Wage losses saved" },
      { metric: "99.2%", label: "Accuracy in symptom matches" },
    ],
  },
  {
    id: "cs-3",
    title: "Corporate Wellness Program",
    tag: "Corporate Deployment",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=600",
    location: "Stoic Tech Global Campus",
    problem: "High employee stress and chronic sedentary habits led to a 22% hike in corporate medical insurance premiums and increased seasonal absenteeism.",
    solution: "Placed 4 interactive kiosks in central cafeteria lobbies, integrating wellness check alerts and anonymous stress consultations.",
    results: [
      { metric: "88%", label: "Employee Engagement" },
      { metric: "14%", label: "Drop in health insurance claims" },
      { metric: "1,200 hrs", label: "Productivity saved" },
      { metric: "91%", label: "Anxiety reduction scores" },
    ],
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "b-1",
    title: "The Future of Rural Care: Bridging the Doctor Shortage with Smart AI",
    category: "Telemedicine",
    excerpt: "How remote kiosk platforms equipped with advanced diagnostic cuffs are bringing specialists to remote communities instantly.",
    author: "Dr. Vikram Aditya",
    role: "CEO & Founder",
    date: "June 18, 2026",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=600",
    content: "The challenge of rural healthcare has always been distribution. In most developing nations, over 70% of specialists reside in Tier-1 metropolitan areas, while 70% of the population lives in rural zones. It is physically impossible to construct hospitals at that scale.\n\nEnter the AI-Assisted Telemedicine Kiosk. By packaging FDA-grade clinical sensors (diastolic/systolic monitors, temporal IR sensors, 12-channel ECGs, and 4K macro camera arrays) into an affordable, rugged, solar-compatible cabinet, we create an immediate virtual clinic. When paired with neural network triage algorithms, we can capture 98% of standard patient diagnostic histories and match them to the correct remote consultant immediately. This isn't just digital health—it's the democratization of clinical care.",
  },
  {
    id: "b-2",
    title: "HIPAA and Telehealth Security: How to Protect Patient Diagnostic Streams",
    category: "Data Security",
    excerpt: "Exploring end-to-end encryption, biometrics, and secure tokenized authentication in clinical kiosks.",
    author: "Ananya Deshmukh",
    role: "Chief Technology Officer",
    date: "June 12, 2026",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=600",
    content: "When building decentralized healthcare kiosks, security cannot be an afterthought. Every heartbeat recorded, every blood pressure wave generated, and every video file streamed constitutes highly sensitive Protected Health Information (PHI). Under regulatory frameworks like HIPAA and GDPR, exposing this data triggers massive penalties and destroys client trust.\n\nAt MediConnect, we employ a triple-lock system. First, all sensor data is compiled at the local edge, encrypted using AES-256 GCM, and transmitted via TLS 1.3. Second, we bypass standard passwords entirely, utilizing secure OAuth 2.0 biometric login (fingerprint scans or secure card chips) to confirm patient identity. Third, our database operates on zero-trust architectures, ensuring that only licensed medical professionals linked to that specific consult token have decryption keys to view history logs.",
  },
  {
    id: "b-3",
    title: "Reducing OPD Waiting Times by 70%: AI Triaging in Public Hospitals",
    category: "Healthcare Innovation",
    excerpt: "How hospital extension kiosks are filtering low-risk symptoms to relieve crowded emergency lobbies.",
    author: "Dr. Laura Vance",
    role: "MD, Chief Medical Advisor",
    date: "May 28, 2026",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1538108149393-fdfd81691435?auto=format&fit=crop&q=80&w=600",
    content: "Walk into any public hospital lobby on a Monday morning and you are greeted with overcrowding. Outpatient Departments (OPD) are flooded with people waiting hours for simple fever scans or prescription renewals. This severely degrades physician attention spans and delays critical care.\n\nBy placing hospital extension kiosks in our lobby halls, we change the queue equation. The patient interacts with the touchscreen, logs their vitals in 3 minutes, and types in symptoms. If the AI detects normal ranges and a low-risk profile, it routes the patient directly to our remote virtual clinic doctor. The patient gets their advice and printed prescription in 8 minutes, leaving the physical hospital desks clear to process complex trauma and critical cases.",
  },
];
